---
title: "Homework_03"
author: "Molly Ratliff"
date: "2024-01-31"
output: 
  html_document: 
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**1. Transform aligned columns to the proper format for a .csv file.**
```
FIND:\s{2,} 
REPLACE:,
```
The find command searches for any spaces between two to eleven units long. It maintains single spaces between words in the same column, while getting rid of extra spaces between columns. These spaces are replaced with a comma. 

**2. Format names without commas and put institution in parentheses**
```
FIND:(\w*),\s(\w*),\s(.*)
REPLACE:\2 \1 (\3)
```
The find command captures the first one or more word characters followed by a comma and space. It then captures the second one or more word characters followed by a comma and space. The remaining characters are captured as the third unit. The first and second captures are switched and the third capture is put in parentheses. 

**3. Place each fiddle tune and corresponding four digit number on its own line**
```
FIND:.mp3 
REPLACE:.mp3\n
```
The find command captures a word character followed by a space followed by a word character followed by a space followed by a word character then the text .mp3 followed by a space. A new line return is made after each capture.

**4. Write an expression to move the four digit number to the end of the song title**
```
FIND:(\w+)\s(.*)(\.mp3)
REPLACE:\2_\1\3
```
This find command breaks each line into one capture with the number, one capture with the song title, and one capture with the file extension. Then, the captures are rearranged so the song title is first, followed by the number with an underscore and the file extension.

**5. Write an expression to rearrange genus, species, and two numeric variables.**
```
FIND:(\w)(\w+),(\w+),(\d+\.\d+),(\d+)
REPLACE:\1_\3,\5
```
This find command breaks the first letter of the genus, remainder of the genus, species, first set of digits, and second set of digits into separate captures. The output is the first letter of the genus, the species, and the last number. 

**6. Using the original data set from question 5, write the abbreviated version of the species names**
```
FIND:(\w)\w+,(\w{4})\w+,\d+.\d+,(\d+)
REPLACE:\1_\2,\3
```
This find commands captures the first letter of the genus and first four letters of the species. The last capture is the final number in each row. The output is each of these captured units separated by an underscore and comma. 

**7. Using the original data set from question 5, fuse the species and genus name, followed by two columns of the numeric data**
```
FIND:(\w{3})\w+,(\w{3})\w+,(\d+\.\d+),(\d+)
REPLACE:\1\2, \4, \3
```
This find command captures the first three characters from the genus and species and the two numbers individually. The output combines the first three letters of genus and species, then arranges the two numbers into two columns
